# Site settings
title: Engineering OS
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pierremary.com" # the base hostname & protocol for your site
twitter_username: _PierreMary
github_username:  pmary

defaults:
- scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'en/posts/:title'
    language: en
- scope:
    path: '_posts/fr'
    type: 'posts'
  values:
    permalink: 'fr/posts/:title'
    language: fr

# Build settings
markdown: kramdown
highlighter: rouge

show_newsletter: false

kramdown:
  input: GFM
  syntax_highlighter: rouge
